import axios from 'axios';
// Import the centralized configuration
import Config from '../../constants/Config';

/**
 * API_BASE is now dynamically generated by Config.js.
 * To change from Local to Production, edit 'ENV' in constants/Config.js.
 */
export const API_BASE = Config.getApiUrl();

const api = axios.create({
    baseURL: API_BASE,
    withCredentials: true,
    headers: {
        'Content-Type': 'application/json',
        'Accept': 'application/json',
    },
});

export default api;